apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cart.name" .}}
  labels: {{ include "cart.labels" . | nindent 4 }}
  # namespace: roboshop
data:
  REDIS_HOST: {{ .Values.configMap.REDIS_HOST | quote }}
  CATALOGUE_HOST: {{ .Values.configMap.CATALOGUE_HOST | quote }}
  CATALOGUE_PORT: {{ .Values.configMap.CATALOGUE_HOST | quote }}
