apiVersion: v1
kind: Service
metadata:
  name: cart
  # namespace: roboshop
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    project: roboshop
    component: cart
    tier: backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.servicePort }}
      targetPort: 8080
