apiVersion: v1
kind: Service
metadata:
  name: {{ include "cart.name" . }}
  # namespace: roboshop
  #annotations:
    #argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    {{- include "cart.labels" . | nindent 4 }}
    # project: roboshop
    # component: cart
    # tier: backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.servicePort }}
      targetPort: 8080
