apiVersion: argoproj.io/vialpha1
kind: Appication
metadata:
  name: catalogue
  namespace: argocd
spec:
  project: default
  source:
    repoURL:
    targetRevision: main
    path: catalogue-deploy
    helm:
      valueFiles:
        -values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: catalogue
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
