apiVersion: argoproj.io/vialpha1
kind: Appication
metadata:
  name: frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL:
    targetRevision: main
    path: frontend-deploy
    helm:
      valueFiles:
        -values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: frontend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
