apiVersion: argoproj.io/vialpha1
kind: Appication
metadata:
  name: payment
  namespace: argocd
spec:
  project: default
  source:
    repoURL:
    targetRevision: main
    path: payment-deploy
    helm:
      valueFiles:
        -values-dev.yaml
  destination:
    server:
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
