apiVersion: argoproj.io/vialpha1
kind: Appication
metadata:
  name: shipping
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Rohith1845/k8-components-deploy.git
    targetRevision: main
    path: shipping-deploy
    helm:
      valueFiles:
        -values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: shipping
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
